#!/usr/bin/env python3
"""Generate 16x16 pixel motif icons for NOU enemies (scaled to 64x64 PNG)."""
from pathlib import Path
from PIL import Image

SCALE = 4
OUT = Path(__file__).resolve().parent.parent / "assets" / "icons"

COLORS = {
    ".": (0, 0, 0, 0),
    "R": (229, 9, 20, 255),
    "r": (180, 20, 30, 255),
    "W": (255, 255, 255, 255),
    "G": (170, 170, 180, 255),
    "g": (110, 110, 120, 255),
    "D": (45, 45, 55, 255),
    "Y": (255, 210, 60, 255),
    "O": (255, 140, 50, 255),
    "P": (244, 114, 182, 255),
    "p": (190, 60, 110, 255),
    "B": (56, 140, 220, 255),
    "b": (30, 80, 160, 255),
    "C": (160, 90, 50, 255),
    "c": (120, 60, 30, 255),
    "L": (80, 180, 60, 255),
    "A": (220, 45, 45, 255),
    "a": (160, 30, 30, 255),
    "K": (30, 30, 35, 255),
    "T": (255, 180, 80, 255),
    "t": (200, 130, 50, 255),
    "F": (240, 220, 200, 255),
    "f": (210, 185, 165, 255),
    "S": (200, 200, 210, 255),
    "s": (140, 140, 155, 255),
    "H": (255, 230, 200, 255),
    "N": (255, 200, 180, 255),
    "n": (220, 150, 130, 255),
}

ICONS = {
    "lips": [
        "................",
        "................",
        "................",
        "....PPPPPPPP....",
        "...PPPPPPPPPP...",
        "..PPPPPPPPPPPP..",
        "..PPPP....PPPP..",
        "...PP......PP...",
        "...PP......PP...",
        "..PPPP....PPPP..",
        "...PPPPPPPPPP...",
        "....PPPPPPPP....",
        "................",
        "................",
        "................",
        "................",
    ],
    "ear": [
        "................",
        "................",
        "......FFFF......",
        ".....FFFFFFF....",
        "....FFFFFFFFF...",
        "...FFFFFFFFFF...",
        "...FFFFFFFFFF...",
        "...FFFFFFFFFF...",
        "...FFFFFFFFFF...",
        "....FFFFFFFFF...",
        ".....FFFFFFF....",
        "......FFFFF.....",
        ".......FFF......",
        "........F.......",
        "................",
        "................",
    ],
    "eyeball": [
        "................",
        "................",
        ".....WWWWWW.....",
        "...WWWWWWWWWW...",
        "..WWWWWWWWWWWW..",
        ".WWWWWWWWWWWWWW.",
        ".WWWWRRRRRRWWWW.",
        ".WWWWRRRRRRWWWW.",
        ".WWWWRRRRRRWWWW.",
        ".WWWWWWWWWWWWWW.",
        "..WWWWWWWWWWWW..",
        "...WWWWWWWWWW...",
        ".....WWWWWW.....",
        "................",
        "................",
        "................",
    ],
    "fingernail": [
        "................",
        "................",
        "................",
        "........NNNN....",
        ".......NNNNN....",
        "......NNNNNN....",
        ".....NNNNNNN....",
        "....NNNNNNNN....",
        "...NNNNNNNNN....",
        "..NNNNNNNNNN....",
        ".NNNNNNNNNNN....",
        "NNNNNNNNNNNN....",
        "NNNNNNNNNNNN....",
        ".NNNNNNNNNNN....",
        "..NNNNNNNNN.....",
        "...NNNNNNN......",
    ],
    "hourglass": [
        "................",
        "................",
        "....YYYYYY......",
        "...YYYYYYYY.....",
        "..YYYYYYYYYY....",
        "...YYYYYYYY.....",
        "....YYYYYY......",
        ".....YYYY.......",
        ".....YYYY.......",
        "....YYYYYY......",
        "...YYYYYYYY.....",
        "..YYYYYYYYYY....",
        "...YYYYYYYY.....",
        "....YYYYYY......",
        "................",
        "................",
    ],
    "apple": [
        "................",
        ".......LL.......",
        "......LLLL......",
        ".....AAAAAA.....",
        "....AAAAAAAA....",
        "...AAAAAAAAAA...",
        "...AAAAAAAAAA...",
        "...AAAAAAAAAA...",
        "...AAAAAAAAAA...",
        "....AAAAAAAA....",
        ".....AAAAAA.....",
        "......AAAA......",
        "................",
        "................",
        "................",
        "................",
    ],
    "book": [
        "................",
        "................",
        "....CCCCCCCC....",
        "...CCCCCCCCCC...",
        "...CCWWWWWWCC...",
        "...CCWWWWWWCC...",
        "...CCWWWWWWCC...",
        "...CCWWWWWWCC...",
        "...CCWWWWWWCC...",
        "...CCWWWWWWCC...",
        "...CCCCCCCCCC...",
        "....CCCCCCCC....",
        "................",
        "................",
        "................",
        "................",
    ],
    "tiger": [
        "................",
        "................",
        "..TTTTTTTTTTTT..",
        ".TTTTTTTTTTTTTT.",
        ".TTTWWWWWWWWTTT.",
        ".TTWWRRRRRRWWTT.",
        ".TTWRRRRRRRRWTT.",
        ".TTWWRRRRRRWWTT.",
        ".TTTWWWWWWWWTTT.",
        ".TTTTTTTTTTTTTT.",
        "..TTTTTTTTTTTT..",
        "...TTT....TTT...",
        "................",
        "................",
        "................",
        "................",
    ],
    "spike": [
        "................",
        ".......GG.......",
        "......GGGG......",
        ".....GGGGGG.....",
        "....GGGGGGGG....",
        "...GGGGGGGGGG...",
        "..GGGGGGGGGGGG..",
        ".GGGGGGGGGGGGGG.",
        "..GGGGGGGGGGGG..",
        "...GGGGGGGGGG...",
        "....GGGGGGGG....",
        ".....GGGGGG.....",
        "......GGGG......",
        ".......GG.......",
        "................",
        "................",
    ],
    "clock": [
        "................",
        "................",
        ".....SSSSSS.....",
        "...SSSSSSSSSS...",
        "..SSSSSSSSSSSS..",
        ".SSSSSSSSSSSSSS.",
        ".SSSSRR....SSSS.",
        ".SSSS.R....SSSS.",
        ".SSSS..R..SSSSS.",
        ".SSSS....RSSSSS.",
        "..SSSSSSSSSSSS..",
        "...SSSSSSSSSS...",
        ".....SSSSSS.....",
        "................",
        "................",
        "................",
    ],
    "puzzle": [
        "................",
        "................",
        "..BBBBBBBBBB....",
        ".BBBBBBBBBBBB...",
        ".BBBBBBBBBBBB...",
        ".BBBB..BBBBBB...",
        ".BBBBBBBBBBBB...",
        ".BBBBBBBBBBBB...",
        ".BBBBBBBBBBBB...",
        ".BBBB..BBBBBB...",
        ".BBBBBBBBBBBB...",
        "..BBBBBBBBBB....",
        "................",
        "................",
        "................",
        "................",
    ],
    "cigarette": [
        "................",
        "................",
        "................",
        "................",
        "....WWWWWWWWOOOO",
        "...WWWWWWWWOOOOO",
        "...WWWWWWWWOOOOO",
        "....WWWWWWWWOOOO",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
    ],
    "computer": [
        "................",
        "................",
        "....KKKKKKKK....",
        "...KKBBBBBBKK...",
        "...KBBBBBBBBK...",
        "...KBBBBBBBBK...",
        "...KBBBBBBBBK...",
        "...KKBBBBBBKK...",
        "....KKKKKKKK....",
        ".....KKKKKK.....",
        "....KKKKKKKK....",
        "................",
        "................",
        "................",
        "................",
        "................",
    ],
}


def render(name: str, grid: list[str]) -> Image.Image:
    h, w = len(grid), len(grid[0])
    img = Image.new("RGBA", (w * SCALE, h * SCALE), (0, 0, 0, 0))
    px = img.load()
    for y, row in enumerate(grid):
        for x, ch in enumerate(row):
            color = COLORS.get(ch, COLORS["."])
            if color[3] == 0:
                continue
            for sy in range(SCALE):
                for sx in range(SCALE):
                    px[x * SCALE + sx, y * SCALE + sy] = color
    return img


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for name, grid in ICONS.items():
        path = OUT / f"{name}.png"
        render(name, grid).save(path, "PNG")
        print(f"wrote {path}")
    print(f"done: {len(ICONS)} icons")


if __name__ == "__main__":
    main()
